stages:
- build
- cross compile

Build:
  stage: build
  script:
    - cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build --target tgbot

CrossCompile:
  stage: cross compile
  script:
    - cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=cmake/mingw.cmake -DCMAKE_EXE_LINKER_FLAGS="-static" -DCMAKE_BUILD_TYPE=Debug -G Ninja
    - cmake --build build --target tgbot
